name: "🎃 Hacktoberfest 2022"
description: |
  Review the [instructions][i] and file a new issue to tackle quality improvement opportunities for Hacktoberfest!

  [i]: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257
title: "🎃 Hacktoberfest: "
body:
  - type: markdown
    attributes:
      value: |
        This issue's related to [Hacktoberfest 2022][01]. For more info, see the meta-issue below:
        
        - MicrosoftDocs/PowerShell-Docs#9257

        [01]: https://hacktoberfest.com/participation/
  - type: dropdown
    id: QualityArea
    validations:
      required: true
    attributes:
      label: Quality Areas
      description: |
        Select one or more quality areas to improve on with your contribution.

        For more information, see the relevant section in the meta issue:

        - [Aliases][aliases]: Ensure cmdlet aliases are documented
        - [Formatting code samples][code-samples]: Ensure proper casing, line length, etc in code samples
        - [Formatting command syntax][command-syntax]: Ensure proper casing and formatting for command syntax, including cmdlets, types, etc.
        - [Link References][link-refs]: Ensure links in conceptual docs are defined as numbered references
        - [Markdown linting][md-linting]: Ensure content follows markdownlint rules
        - [Spelling][spelling]: Ensure proper casing and spelling for words

        [aliases]: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257#aliases
        [code-samples]: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257#formatting-code-samples
        [command-syntax]: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257#formatting-command-syntax
        [link-refs]: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257#link-references
        [md-linting]: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257#markdown-linting
        [spelling]: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9257#spelling
      multiple: true
      options:
        - Aliases
        - Formatting code samples
        - Formatting command syntax
        - Link References
        - Markdown linting
        - Spelling
  - type: textarea
    id: ArticleList
    validations:
      required: true
    attributes:
      label: Article List
      description: >-
        Specify the articles you are committing to work on, one per line. You can specify each entry
        as a path, the article's title, or the link to the article on Learn. If you specify an
        article by path for a reference article, such as a cmdlet or about topic, specify the
        version segment as `*.*`.
      placeholder: |
        - reference/*.*/Microsoft.PowerShell.Core/Add-History.md
        - Add-History
        - https://learn.microsoft.com/powershell/module/microsoft.powershell.core/add-history
