name: "Hacktoberfest"
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited

jobs:
  # If the PR has a jack-o-lantern in the name, label it as hacktoberfest.
  LabelPullRequestByTitle:
    name: Label PR by title
    if: contains(github.event.pull_request.title, '🎃')
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: hacktoberfest-candidate

  # If the PR gets labeled as hacktoberfest, add it to the project
  AddPullRequestToProject:
    name: Add pull request to project
    runs-on: ubuntu-latest
    needs: LabelPullRequestByTitle
    if: |
      contains(github.event.pull_request.labels.*.name, 'hacktoberfest-candidate')
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/michaeltlombardi/projects/1
          github-token: ${{ secrets.hacktober_token }}
