name: "Hacktoberfest Issues"
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  # Assign an issue to the author if the body text matches text inserted from the issue template.
  IsHacktoberFestIssue:
    name: Verify issue is for hacktoberfest
    runs-on: ubuntu-latest
    outputs:
      check: ${{ steps.is-hacktober.outputs.match != '' }}
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: is-hacktober
        with:
          text: ${{ github.event.issue.body }}
          regex: "🎃 2022: Foo"
          flags: gm

  AssignIssue:
    name: Assign Issue
    needs: IsHacktoberFestIssue
    if: needs.IsHacktoberFestIssue.outputs.check
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.event.issue.user.login }}

  # Associate the issue with the meta issue and assign it to the author if the body text matches text inserted from the issue
  AssociateIssue:
    name: Associate Issue
    needs: IsHacktoberFestIssue
    if: needs.IsHacktoberFestIssue.outputs.check
    runs-on: windows-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: body-associated
        with:
          text: ${{ github.event.issue.body }}
          regex: '^- michaeltlombardi\/ghe#26$'
      - if: steps.body-associated.outputs.match == ''
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          BODY: ${{ github.event.issue.body }}
          PREFIX: |
            This issue's related to [Hacktoberfest 2022][01]. For more info, see the meta-issue below:

            - michaeltlombardi/ghe#26

            [01]: https://hacktoberfest.com/participation/
        run: |
          $env:PREFIX, $env:BODY
          | Join-String -Separator "`n`n"
          | Out-File -FilePath combined.txt -Encoding utf8

          gh issue edit $env:ISSUE --body-file combined.txt

  LabelIssue:
    name: Label Issue
    needs: IsHacktoberFestIssue
    if: needs.IsHacktoberFestIssue.outputs.check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - regex: Aliases
            label: quality-aliases
          - regex: Formatting code samples
            label: quality-format-code-samples
          - regex: Formatting command syntax
            label: quality-format-command-syntax
          - regex: Link references
            label: quality-link-references
          - regex: Markdown linting
            label: quality-markdownlint
          - regex: Spelling
            label: quality-spelling
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: matcher
        with:
          text: ${{ github.event.issue.body }}
          regex: '^### Quality Areas\s*^.*${{ matrix.regex }}.*$'
          flags: gm
      - uses: actions-ecosystem/action-add-labels@v1
        if: steps.matcher.outputs.match != ''
        with:
          labels: ${{ matrix.label }}
