name: "Hacktoberfest"
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  labeling:
    name: Issue Labeling
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeling/hackoberfest.yml
        enable-versioned-regex: 0
