name: "Hacktoberfest"
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  labeling:
    name: Issue Labeling
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-regex-match@v2
      id: shouldLabelAliases
      with:
        text: ${{ github.event.issue.body }}
        regex: '^### Quality Areas\\s*^.*Aliases.*$'
        flags: gm
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ steps.shouldLabelAliases.outputs.match != '' }}
      with:
        labels: |
          quality-aliases
    - uses: actions-ecosystem/action-regex-match@v2
      id: shouldLabelFormattingCodeSamples
      with:
        text: ${{ github.event.issue.body }}
        regex: '^### Quality Areas\\s*^.*Formatting Code Samples.*$'
        flags: gm
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ steps.shouldLabelFormattingCodeSamples.outputs.match != '' }}
      with:
        labels: |
          quality-formatting-code-samples
    - uses: actions-ecosystem/action-regex-match@v2
      id: shouldLabelFormattingCommandSyntax
      with:
        text: ${{ github.event.issue.body }}
        regex: '^### Quality Areas\\s*^.*Formatting Command Syntax.*$'
        flags: gm
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ steps.shouldLabelFormattingCommandSyntax.outputs.match != '' }}
      with:
        labels: |
          quality-formatting-command-syntax
    - uses: actions-ecosystem/action-regex-match@v2
      id: shouldLabelLinkReferences
      with:
        text: ${{ github.event.issue.body }}
        regex: '^### Quality Areas\\s*^.*Link References.*$'
        flags: gm
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ steps.shouldLabelLinkReferences.outputs.match != '' }}
      with:
        labels: |
          quality-link-references
    - uses: actions-ecosystem/action-regex-match@v2
      id: shouldLabelMarkdownLinting
      with:
        text: ${{ github.event.issue.body }}
        regex: '^### Quality Areas\\s*^.*Markdown Linting.*$'
        flags: gm
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ steps.shouldLabelMarkdownLinting.outputs.match != '' }}
      with:
        labels: |
          quality-markdown-linting
    - uses: actions-ecosystem/action-regex-match@v2
      id: shouldLabelSpelling
      with:
        text: ${{ github.event.issue.body }}
        regex: '^### Quality Areas\\s*^.*Spelling.*$'
        flags: gm
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ steps.shouldLabelSpelling.outputs.match != '' }}
      with:
        labels: |
          quality-spelling
